[package]
name = "rk-delta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lzzzz = "1.0.3"
base64 = "0.13.0"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "rk"
harness = false
